name: hyphae
base: core24
version: "1.0"
license: BSD-3-Clause
grade: devel
confinement: strict
summary: Cluster SDN underlay built on Tailscale
description: |
  Cluster SDN underlay built on Tailscale

#platforms:
#  amd64:
#  arm64:

plugs:
  sys-devices-virtual-dmi-ids:
    interface: system-files
    read:
      # Tailscale uses this to figure out if running in VM and if so, which Public Cloud
      # https://github.com/tailscale/tailscale/blob/65fe0ba7b50928eff53e2750ff2d583e4a33eb7e/util/cloudenv/cloudenv.go#L115-L126
      # Note that the paths in the source code are symlinks to the corresponding paths below,
      # so we don't need to include the symlinks, just the target files:
      - /sys/devices/virtual/dmi/id/bios_vendor
      - /sys/devices/virtual/dmi/id/product_name
      - /sys/devices/virtual/dmi/id/sys_vendor

slots:
  # Share the socket directory to support the case where another snap needs to communicate with tailscaled.
  socket:
    interface: content
    content: writable-data
    write:
      - $SNAP_COMMON/socket

apps:
  tailscale:
    command: bin/tailscale --socket $SNAP_COMMON/socket/tailscaled.sock
    plugs:
      - network
      - network-bind
  tailscaled:
    # NOTE: cannot use layout to support default socket location, because /var/run is not allowed for layout.
    command: bin/tailscaled --socket $SNAP_COMMON/socket/tailscaled.sock --statedir $SNAP_COMMON --verbose 10
    daemon: simple
    plugs:
      - firewall-control
      - network
      - network-bind
      - network-control
      - sys-devices-virtual-dmi-ids

parts:
  tailscale:
    source: https://github.com/tailscale/tailscale.git
    source-tag: v1.78.1
    plugin: go
    build-snaps:
      - go
    stage-packages:
      - iptables
      - openssh-client  # for tailscale ssh
    override-build: |
      go install -p $CRAFT_PARALLEL_BUILD_COUNT ./cmd/tailscale
      go install -p $CRAFT_PARALLEL_BUILD_COUNT ./cmd/tailscaled
    override-prime: |
      craftctl default
      ln -s xtables-nft-multi $CRAFT_PRIME/usr/sbin/iptables
      ln -s xtables-nft-multi $CRAFT_PRIME/usr/sbin/ip6tables
